-- ============================================================
-- StockCast 분석계 스키마 — Oracle DDL (완성본, 18개 엔터티)
-- 용도: Oracle DB에 적재 후 모델링 툴(SQL Developer Data Modeler 등)에서
--       리버스 엔지니어링하여 ERD(바커/IE 표기) 자동 생성.
-- SAP MM(자재) + PM(설비 유지보수) 구조 차용.
-- 부모→자식 순서로 CREATE. 재실행 시 아래 DROP 주석 해제.
-- ============================================================

-- DROP TABLE maintenance_order_part; DROP TABLE maintenance_order; DROP TABLE equipment;
-- DROP TABLE ext_retail_index; DROP TABLE ext_shop_price; DROP TABLE ext_bid_notice;
-- DROP TABLE ext_holiday; DROP TABLE ext_weather; DROP TABLE stock_snapshot_history;
-- DROP TABLE nfc_tag; DROP TABLE material_doc_item; DROP TABLE material_doc_header;
-- DROP TABLE stock; DROP TABLE movement_type; DROP TABLE material;
-- DROP TABLE material_group; DROP TABLE storage_location; DROP TABLE plant;

CREATE TABLE plant (
  plant_id    VARCHAR2(4)   NOT NULL,
  name        VARCHAR2(60)  NOT NULL,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_plant PRIMARY KEY (plant_id)
);
COMMENT ON TABLE plant IS '사업장/물류센터 (마스터)';

CREATE TABLE storage_location (
  plant_id  VARCHAR2(4)   NOT NULL,
  sloc_id   VARCHAR2(4)   NOT NULL,
  name      VARCHAR2(60)  NOT NULL,
  CONSTRAINT pk_storage_location PRIMARY KEY (plant_id, sloc_id),
  CONSTRAINT fk_sloc_plant FOREIGN KEY (plant_id) REFERENCES plant(plant_id)
);
COMMENT ON TABLE storage_location IS '저장위치/창고 (마스터)';

CREATE TABLE material_group (
  group_code VARCHAR2(9)   NOT NULL,
  name       VARCHAR2(60)  NOT NULL,
  CONSTRAINT pk_material_group PRIMARY KEY (group_code)
);
COMMENT ON TABLE material_group IS '자재그룹 (코드성)';

CREATE TABLE material (
  material_no    VARCHAR2(18)  NOT NULL,
  description    VARCHAR2(120) NOT NULL,
  material_type  VARCHAR2(4)   NOT NULL,
  group_code     VARCHAR2(9),
  base_uom       VARCHAR2(3)   DEFAULT 'EA' NOT NULL,
  unit_price     NUMBER(12,2)  DEFAULT 0   NOT NULL,
  created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_material PRIMARY KEY (material_no),
  CONSTRAINT fk_material_group FOREIGN KEY (group_code) REFERENCES material_group(group_code)
);
COMMENT ON TABLE material IS '자재(품목) 마스터 — 단가 포함';

CREATE TABLE movement_type (
  code        VARCHAR2(3)   NOT NULL,
  description VARCHAR2(60)  NOT NULL,
  direction   NUMBER(3)     NOT NULL,
  CONSTRAINT pk_movement_type PRIMARY KEY (code),
  CONSTRAINT ck_mvt_dir CHECK (direction IN (-1, 1))
);
COMMENT ON TABLE movement_type IS '이동유형 (코드성) 101입고/201출고/561기초';

CREATE TABLE stock (
  material_no       VARCHAR2(18) NOT NULL,
  plant_id          VARCHAR2(4)  NOT NULL,
  sloc_id           VARCHAR2(4)  NOT NULL,
  unrestricted_qty  NUMBER(15,3) DEFAULT 0 NOT NULL,
  safety_stock      NUMBER(15,3) DEFAULT 0 NOT NULL,
  reorder_point     NUMBER(15,3) DEFAULT 0 NOT NULL,
  updated_at        TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_stock PRIMARY KEY (material_no, plant_id, sloc_id),
  CONSTRAINT fk_stock_material FOREIGN KEY (material_no) REFERENCES material(material_no),
  CONSTRAINT fk_stock_sloc FOREIGN KEY (plant_id, sloc_id) REFERENCES storage_location(plant_id, sloc_id)
);
COMMENT ON TABLE stock IS '저장위치별 현재고 + 안전재고/재주문점';

CREATE TABLE material_doc_header (
  doc_no       NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
  posting_date DATE         NOT NULL,
  doc_date     DATE         DEFAULT SYSDATE,
  source       VARCHAR2(10) DEFAULT 'NFC',
  created_at   TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_mdh PRIMARY KEY (doc_no)
);
COMMENT ON TABLE material_doc_header IS '자재문서 헤더 (입출고 1건, 거래)';

CREATE TABLE material_doc_item (
  doc_no        NUMBER(19)   NOT NULL,
  item_no       NUMBER(10)   NOT NULL,
  material_no   VARCHAR2(18) NOT NULL,
  plant_id      VARCHAR2(4)  NOT NULL,
  sloc_id       VARCHAR2(4)  NOT NULL,
  movement_type VARCHAR2(3)  NOT NULL,
  quantity      NUMBER(15,3) NOT NULL,
  uom           VARCHAR2(3)  DEFAULT 'EA',
  CONSTRAINT pk_mdi PRIMARY KEY (doc_no, item_no),
  CONSTRAINT fk_mdi_header FOREIGN KEY (doc_no) REFERENCES material_doc_header(doc_no) ON DELETE CASCADE,
  CONSTRAINT fk_mdi_material FOREIGN KEY (material_no) REFERENCES material(material_no),
  CONSTRAINT fk_mdi_mvt FOREIGN KEY (movement_type) REFERENCES movement_type(code),
  CONSTRAINT fk_mdi_sloc FOREIGN KEY (plant_id, sloc_id) REFERENCES storage_location(plant_id, sloc_id),
  CONSTRAINT ck_mdi_qty CHECK (quantity > 0)
);
COMMENT ON TABLE material_doc_item IS '자재문서 품목 라인 (거래)';

CREATE TABLE nfc_tag (
  tag_uid     VARCHAR2(64) NOT NULL,
  material_no VARCHAR2(18) NOT NULL,
  plant_id    VARCHAR2(4)  NOT NULL,
  sloc_id     VARCHAR2(4)  NOT NULL,
  created_at  TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_nfc_tag PRIMARY KEY (tag_uid),
  CONSTRAINT fk_nfc_material FOREIGN KEY (material_no) REFERENCES material(material_no),
  CONSTRAINT fk_nfc_sloc FOREIGN KEY (plant_id, sloc_id) REFERENCES storage_location(plant_id, sloc_id)
);
COMMENT ON TABLE nfc_tag IS 'NFC 태그 UID - 자재 매핑';

CREATE TABLE stock_snapshot_history (
  snapshot_date    DATE         NOT NULL,
  material_no      VARCHAR2(18) NOT NULL,
  plant_id         VARCHAR2(4)  NOT NULL,
  sloc_id          VARCHAR2(4)  NOT NULL,
  unrestricted_qty NUMBER(15,3) NOT NULL,
  created_at       TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_ssh PRIMARY KEY (snapshot_date, material_no, plant_id, sloc_id),
  CONSTRAINT fk_ssh_material FOREIGN KEY (material_no) REFERENCES material(material_no),
  CONSTRAINT fk_ssh_sloc FOREIGN KEY (plant_id, sloc_id) REFERENCES storage_location(plant_id, sloc_id)
);
COMMENT ON TABLE stock_snapshot_history IS '월말 재고 스냅샷 (이력성)';

CREATE TABLE ext_weather (
  obs_date    DATE          NOT NULL,
  region_code VARCHAR2(10)  DEFAULT '108',
  avg_temp    NUMBER(5,2),
  min_temp    NUMBER(5,2),
  max_temp    NUMBER(5,2),
  precip_mm   NUMBER(6,2),
  CONSTRAINT pk_ext_weather PRIMARY KEY (obs_date)
);
COMMENT ON TABLE ext_weather IS '기상청 일별 날씨 (외부 공공데이터)';

CREATE TABLE ext_holiday (
  holiday_date DATE          NOT NULL,
  name         VARCHAR2(60)  NOT NULL,
  is_holiday   NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT pk_ext_holiday PRIMARY KEY (holiday_date),
  CONSTRAINT ck_holiday_bool CHECK (is_holiday IN (0, 1))
);
COMMENT ON TABLE ext_holiday IS '공휴일 (외부 공공데이터, 코드성)';

CREATE TABLE ext_bid_notice (
  bid_no        VARCHAR2(40)  NOT NULL,
  bid_ord       VARCHAR2(10)  DEFAULT '00' NOT NULL,
  bid_name      VARCHAR2(300),
  notice_agency VARCHAR2(120),
  demand_agency VARCHAR2(120),
  est_price     NUMBER(18,2),
  notice_date   DATE,
  category      VARCHAR2(40)  DEFAULT '물품',
  CONSTRAINT pk_ext_bid PRIMARY KEY (bid_no, bid_ord)
);
COMMENT ON TABLE ext_bid_notice IS '나라장터 물품 입찰공고 (외부 공공데이터, 실수요)';

CREATE TABLE ext_shop_price (
  id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
  spec_name       VARCHAR2(300),
  corp_name       VARCHAR2(120),
  maker_name      VARCHAR2(120),
  contract_price  NUMBER(15,2),
  unit            VARCHAR2(20),
  contract_method VARCHAR2(40),
  enterprise_div  VARCHAR2(40),
  delivery_days   NUMBER(10),
  CONSTRAINT pk_ext_shop PRIMARY KEY (id)
);
COMMENT ON TABLE ext_shop_price IS '조달청 종합쇼핑몰 MAS 계약단가 (외부 공공데이터, 실가격)';

CREATE TABLE ext_retail_index (
  period      VARCHAR2(6)   NOT NULL,
  category    VARCHAR2(60)  DEFAULT '의복' NOT NULL,
  index_value NUMBER(8,2),
  unit        VARCHAR2(20),
  CONSTRAINT pk_ext_retail PRIMARY KEY (period, category)
);
COMMENT ON TABLE ext_retail_index IS '통계청 KOSIS 소매판매지수 (외부 공공데이터, 선택)';


-- ============================================================
-- 설비 유지보수 (SAP PM 구조 차용) — 3개 엔터티
-- 물류센터 설비가 멈추면 입출고 처리량이 멈춘다 → 설비 가동률은 재고 회전의 선행지표.
-- 정비오더 완료 시 사용 부품이 이동유형 261로 material_doc_item에 전기되어
-- 실제 재고가 차감된다(PM ↔ MM 연결점).
-- ============================================================

CREATE TABLE equipment (
  equipment_no   VARCHAR2(18)  NOT NULL,
  name           VARCHAR2(120) NOT NULL,
  category       VARCHAR2(20)  NOT NULL,
  plant_id       VARCHAR2(4)   NOT NULL,
  sloc_id        VARCHAR2(4)   NOT NULL,
  manufacturer   VARCHAR2(60),
  install_date   DATE,
  status         VARCHAR2(6)   DEFAULT 'RUN' NOT NULL,
  pm_cycle_days  NUMBER(10)    DEFAULT 0 NOT NULL,
  last_pm_date   DATE,
  created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_equipment  PRIMARY KEY (equipment_no),
  CONSTRAINT fk_equip_sloc FOREIGN KEY (plant_id, sloc_id)
    REFERENCES storage_location (plant_id, sloc_id),
  CONSTRAINT ck_equip_status CHECK (status IN ('RUN','CHECK','DOWN','SCRAP')),
  CONSTRAINT ck_equip_cycle  CHECK (pm_cycle_days >= 0)
);
COMMENT ON TABLE  equipment IS '설비 마스터 (SAP EQUI+EQKT)';
COMMENT ON COLUMN equipment.status        IS 'RUN 정상 / CHECK 점검중 / DOWN 고장 / SCRAP 폐기';
COMMENT ON COLUMN equipment.pm_cycle_days IS '예방정비 주기(일). 0이면 PM 비대상';
COMMENT ON COLUMN equipment.last_pm_date  IS '최근 예방정비일 — 다음 예정일 = last_pm_date + pm_cycle_days';

CREATE TABLE maintenance_order (
  order_no       NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
  equipment_no   VARCHAR2(18)  NOT NULL,
  order_type     VARCHAR2(2)   DEFAULT 'PM'  NOT NULL,
  status         VARCHAR2(6)   DEFAULT 'REQ' NOT NULL,
  priority       VARCHAR2(1)   DEFAULT 'M'   NOT NULL,
  title          VARCHAR2(200) NOT NULL,
  description    VARCHAR2(500),
  requester      VARCHAR2(40),
  request_date   DATE          NOT NULL,
  planned_date   DATE,
  completed_date DATE,
  labor_cost     NUMBER(14,2)  DEFAULT 0,
  created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_maint_order   PRIMARY KEY (order_no),
  CONSTRAINT fk_maint_equip   FOREIGN KEY (equipment_no)
    REFERENCES equipment (equipment_no),
  CONSTRAINT ck_maint_type    CHECK (order_type IN ('PM','CM')),
  CONSTRAINT ck_maint_status  CHECK (status IN ('REQ','WIP','DONE','CANCEL')),
  CONSTRAINT ck_maint_prio    CHECK (priority IN ('H','M','L'))
);
COMMENT ON TABLE  maintenance_order IS '정비오더 (SAP AUFK/AFIH) — 요청→진행→완료';
COMMENT ON COLUMN maintenance_order.order_type   IS 'PM 예방정비 / CM 사후정비(고장)';
COMMENT ON COLUMN maintenance_order.planned_date IS '정비 예정일 — 지연 판정 기준';

CREATE TABLE maintenance_order_part (
  order_no      NUMBER(19)    NOT NULL,
  item_no       NUMBER(10)    NOT NULL,
  material_no   VARCHAR2(18)  NOT NULL,
  quantity      NUMBER(15,3)  NOT NULL,
  uom           VARCHAR2(3)   DEFAULT 'EA' NOT NULL,
  posted_doc_no NUMBER(19),
  CONSTRAINT pk_maint_part  PRIMARY KEY (order_no, item_no),
  CONSTRAINT fk_part_order  FOREIGN KEY (order_no)
    REFERENCES maintenance_order (order_no),
  CONSTRAINT fk_part_mat    FOREIGN KEY (material_no)
    REFERENCES material (material_no),
  CONSTRAINT ck_part_qty    CHECK (quantity > 0)
);
COMMENT ON TABLE  maintenance_order_part IS '정비 사용자재 (SAP RESB → MSEG 소비)';
COMMENT ON COLUMN maintenance_order_part.posted_doc_no
  IS '전기된 자재문서 번호(이동유형 261). NULL이면 아직 재고에서 빠지지 않은 예약 상태';
